	include m3p4.asm
	Obstaculo macro posX,color
		;y max 187
		xor ax,ax
		xor bx,bx
		xor cx,cx
		xor dx,dx
		mov ax,posX
		PintarRango posX,170,185,color
		mov ax,posX
		add ax,1
		PUNTO ax,169,color
		mov ax,posX
		add ax,1
		PUNTO ax,172,color
		mov ax,2
		add ax,posX
		mov bx,ax
		add bx,7
		PintarHorizontal ax,bx,168,color
		mov ax,2
		add ax,posX
		mov bx,ax
		add bx,7
		PintarHorizontal ax,bx,173,color
		mov ax,10
		add ax,posX
		PUNTO ax,169,color
		mov ax,10
		add ax,posX
		PUNTO ax,172,color
		mov ax,posX
		add ax,11
		PintarRango ax,170,185,color
		mov ax,1
		add ax,posX
		PUNTO ax,183,color
		mov ax,1
		add ax,posX
		PUNTO ax,186,color
		mov ax,	posX
		add ax,2
		mov bx,ax
		add bx,7
		PintarHorizontal ax,bx,182,color
		mov ax,posX
		add ax,2
		mov bx,ax
		add bx,7
		PintarHorizontal ax,bx,187,color
		mov ax,10
		add ax,posX
		PUNTO ax,183,color
		mov ax,10
		add ax,posX
		PUNTO ax,186,color
	endm
	Nube macro posX,color
		;160 pos max y
		mov ax,posx
		add ax,3
		mov bx,ax
		add bx,17
		PintarHorizontal ax,bx,160,color
		mov ax,posx
		add ax,2
		PUNTO ax,159,color
		mov ax,posx
		add ax,21
		PUNTO ax,159,color
		mov ax,posx
		add ax,1
		PUNTO ax,158,color
		mov ax,posx
		add ax,22
		PUNTO ax,158,color
		mov ax,posx
		PintarRango ax,155,157,color
		mov ax,posx
		add ax,23
		PintarRango ax,155,157,color
		mov ax,posx
		add ax,1
		PUNTO ax,154,color
		mov ax,posx
		add ax,22
		PUNTO ax,154,color
		mov ax,posx
		add ax,2
		mov bx,ax
		add bx,2
		PintarHorizontal ax,bx,153,color
		mov ax,posx
		add ax,5
		PintarRango ax,151,152,color
		mov ax,posx
		add ax,6
		mov bx,ax
		add bx,2
		PintarHorizontal ax,bx,150,color
		mov ax,posx
		add ax,9
		PUNTO ax,149,color
		mov ax,posx
		add ax,10
		PUNTO ax,148,color
		mov ax,posx
		add ax,11
		PUNTO ax,147,color
		mov ax,posx
		add ax,12
		mov bx,ax
		add bx,2
		PintarHorizontal ax,bx,146,color
		mov ax,posx
		add ax,15
		PUNTO ax,147,color
		mov ax,posx
		add ax,16
		PUNTO ax,148,color
		mov ax,posx
		add ax,17
		PUNTO ax,149,color
		mov ax,posx
		add ax,18
		PintarRango ax,150,152,color
		mov ax,posx
		add ax,19
		mov bx,ax
		add bx,1
		PintarHorizontal ax,bx,152,color
		mov ax,posx
		add ax,21
		PUNTO ax,153,color
		mov ax,posx
		add ax,22
		PUNTO ax,154,color
	endm